### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by PaleBluDot** [aclu-national/email-builder#32]

**Comment by hellogoodbyte** [comment]
You are receiving this message because you signed up to receive emails from the American Civil Liberties Union.

Please note: If you forward or distribute, the links will open a page with your information filled in.

This email was sent to: dev_sd@aclu.org  ■  Privacy policy | Unsubscribe

ACLU of Utah | 355 North 300 West | Salt Lake City, UT 84103

**Comment by hellogoodbyte** [comment]
You are receiving this message because you signed up to receive emails from the American Civil Liberties Union. Please note: If you forward or distribute, the links will open a page with your information filled in.

This email was sent to: dev_sd@aclu.org  ■  Privacy policy | Unsubscribe

ACLU of Utah | 355 North 300 West | Salt Lake City, UT 84103

**Comment by hellogoodbyte** [comment]
You received this message because dev_sd@aclu.org was signed up to receive emails from the American Civil Liberties Union. Please note: If you forward or distribute, the links will open a page with your information filled in.

ACLU of Utah, 355 North 300 West, Salt Lake City, UT 84103

Privacy policy | Unsubscribe

**Comment by hellogoodbyte** [comment]
Reduced size of header font and used one-line affiliate logo
